export const canadianUniversities = [
    "Acadia University",
    "Algoma University",
    "Athabasca University",
    "Bishop's University",
    "Brandon University",
    "Brescia University College",
    "Brock University",
    "Campion College",
    "Canadian Mennonite University",
    "Cape Breton University",
    "Carleton University",
    "Concordia University",
    "Dalhousie University",
    "Emily Carr University of Art and Design",
    "First Nations University of Canada",
    "Huron University College",
    "King's University College",
    "Kwantlen Polytechnic University",
    "Lakehead University",
    "Laurentian University",
    "MacEwan University",
    "McGill University",
    "McMaster University",
    "Memorial University of Newfoundland",
    "Mount Allison University",
    "Mount Royal University",
    "Mount Saint Vincent University",
    "Nipissing University",
    "NSCAD University",
    "OCAD University",
    "Queen's University",
    "Royal Military College of Canada",
    "Royal Roads University",
    "Ryerson University (now Toronto Metropolitan University)",
    "Saint Mary's University",
    "Simon Fraser University",
    "St. Francis Xavier University",
    "St. Thomas University",
    "The King's University",
    "Thompson Rivers University",
    "Trent University",
    "Université de Moncton",
    "Université de Montréal",
    "Université de Sherbrooke",
    "Université du Québec",
    "Université Laval",
    "University of Alberta",
    "University of British Columbia",
    "University of Calgary",
    "University of Guelph",
    "University of King's College",
    "University of Lethbridge",
    "University of Manitoba",
    "University of New Brunswick",
    "University of Northern British Columbia",
    "University of Ottawa",
    "University of Prince Edward Island",
    "University of Regina",
    "University of Saskatchewan",
    "University of St. Michael's College",
    "University of Sudbury",
    "University of Toronto",
    "University of Trinity College",
    "University of Victoria",
    "University of Waterloo",
    "University of Windsor",
    "University of Winnipeg",
    "Vancouver Island University",
    "Victoria University",
    "Western University",
    "Wilfrid Laurier University",
    "York University"
  ];
  